{% set name = "pytmc" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pytmc/archive/v{{ version }}.tar.gz
  sha256: d308c0d745a269fcb47b23e8b56e8bd0eeca6d8994e193170c93d2323efdf43c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytmc = pytmc.bin.pytmc:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5

test:
  imports:
    - pytmc
  requires:
    - pytest
    - pytest-qt
    - qtpy
    - pyqt >=5

about:
  home: https://github.com/pcdshub/pytmc
  doc_url: https://pcdshub.github.io/pytmc/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Generate EPICS IOCs and records from Beckhoff TwinCAT projects

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
    - n-wbrown
