{% set name = "pytmc" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/pytmc/archive/v{{ version }}.tar.gz
  sha256: 7ca20267450f730dc9111bc1d4a8fe5c5570029700c460d50dd9151344ae4594

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytmc = pytmc.bin.pytmc:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5
  run_constrained:
    - pyqt =5

test:
  imports:
    - pytmc
  requires:
    - pytest
    - pytest-qt
    - qtpy
    - pyqt =5

about:
  home: https://github.com/pcdshub/pytmc
  doc_url: https://pcdshub.github.io/pytmc/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Generate EPICS IOCs and records from Beckhoff TwinCAT projects

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
