{% set name = "pytmc" %}
{% set version = "2.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/pytmc/archive/v{{ version }}.tar.gz
  sha256: fab425fc072b10a9ff141b1a1fd54abdccc0d7af2f4ca63e63a05a2228da9fff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytmc = pytmc.bin.pytmc:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5

test:
  imports:
    - pytmc
  requires:
    - pytest
    - pytest-qt
    - qtpy
    - pyqt >=5

about:
  home: https://github.com/slaclab/pytmc
  doc_url: https://slaclab.github.io/pytmc/
  license: SLAC Open
  license_family: Other
  license_file: LICENSE
  summary: Generate EPICS IOCs and records from Beckhoff TwinCAT projects

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
    - n-wbrown
